Added Recipe ContextType with tests
Torann/json-ld pull request #46
Opened 2019-02-06 03:29 UTC by hollodk

I have added the Recipe ContextType if you like that.

2019-02-06 22:32 UTC, boly38 requested changes
Thanks for the work. Need some minor changes for me 👍😃

2019-02-06 22:32 UTC, boly38 commented on src/ContextTypes/Recipe.php
> +     * reference: https://schema.org/Recipe (alphabetical order)
would be great to respect alphabetical order or remove this tips ;)

2019-02-06 22:32 UTC, boly38 commented on src/ContextTypes/Recipe.php
> +        'name' => null,
you must not repeat an entry that already exists in parents (Creative Work or Thing).

2019-02-06 22:32 UTC, boly38 commented on src/ContextTypes/Recipe.php
> +        'prepTime' => null,
some attributes seems to be related to an intermediate ContextType called 'HowTo'

Thing > Creative Work > HowTo > Recipe

cf. https://schema.org/HowTo

Maybe move theses attributes into this new contextType is better for future improvements / addition.

2019-02-06 22:32 UTC, boly38 commented on src/ContextTypes/Recipe.php
> +        'totalTime' => null,
HowTo

2019-02-06 22:32 UTC, boly38 commented on src/ContextTypes/Recipe.php
> +        'image' => null,
already in 'Thing' parent context type

etc..

2019-02-06 22:32 UTC, boly38 commented on tests/ContextTypes/RecipeTest.php
> +    public function shouldHaveUrl()
change method name because you are expecting a recipe not an url

2019-02-06 22:41 UTC, boly38 commented on src/ContextTypes/NutritionInformation.php
> +class NutritionInformation extends AbstractContext
seems a child of'Thing' ?
https://schema.org/NutritionInformation

and test? :p

2020-03-10 17:30 UTC, Torann commented
Recipe was added in version 0.0.19

2020-03-10 17:30 UTC, closed without merging